name: build swpwn docker image
on:
  push:
    branches: main
  schedule:
    - cron: '0 0 1 * *'

jobs:
  all:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        VERSION: ["16.04","18.04", "20.04"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: build and push ubuntu ${{ matrix.VERSION }}
        uses: docker/build-push-action@v1
        with:
          username: beswing
          password: ${{secrets.DOCKER_HUB_TOKEN}}
          dockerfile: ./build/ubuntu${{ matrix.VERSION }}/dockerfile
          repository: beswing/swpwn
          tags: ${{ matrix.VERSION }}
          tag_with_ref: true
          push: true
