name: build swpwn docker image
on:
  push:
    branches: main
  schedule:
    - cron: '0 0 1 * *'

jobs:
  all:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        VERSION: ["18.04", "20.04"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Dockerhub
        with:
          username: beswing
          password: ${{secrets.DOCKER_HUB_TOKEN}}

      - name: Build and push ubuntu ${{ matrix.VERSION }}
        uses: docker/build-push-action@v2
        with:
          file: ./build/ubuntu${{ matrix.VERSION }}/dockerfile
          tags: beswing/swpwn:${{ matrix.VERSION }}
          push: true
